region: embrach
zip: 8424
start_date: 2025-01-01
end_date: 2025-12-31

collections:
  waste:
    - area: Ost
      schedule:
        - weekly every Tuesday
    - area: West
      schedule:
        - weekly every Friday
        - 2025-04-17 # Ersatzdatum für Karfreitag
        - 2025-07-31 # Ersatzdatum für 1. August, Freitag
        - 2025-12-24 # Ersatzdatum für Stephanstag, Freitag

  bulky_goods:
    - area: Ost
      schedule:
        - weekly every Tuesday
    - area: West
      schedule:
        - weekly every Friday
        - 2025-04-17 # Ersatzdatum für Karfreitag
        - 2025-07-31 # Ersatzdatum für 1. August, Freitag
        - 2025-12-24 # Ersatzdatum für Stephanstag, Freitag
  
  organic:
    - area: Ost
      schedule:
        - every other Wednesday in Jan and Feb starting jan 15th
        - every Wednesday from feb 28th until December 
        - every other Wednesday in Dec
    - area: West
      schedule:
        - every other Monday in Jan and Feb starting jan 13th
        - every Monday from feb 26th until December
        - every other Monday in Dec
        - 2025-04-23 # Ersatzdatum für Ostermontag
        - 2025-06-11 # Ersatzdatum für Pfingstmontag

  metal:
    - schedule:
        - 2025-01-16
        - 2025-02-13
        - 2025-03-27
        - 2025-04-24
        - 2025-05-22
        - 2025-06-19
        - 2025-07-17
        - 2025-08-14
        - 2025-09-25
        - 2025-10-23
        - 2025-11-20
        - 2025-12-18

  paper:
    - schedule:
        - every first Saturday of the month
  
  cardboard:
    - schedule:
        - every other Thurday starting jan 9th
        - 2025-04-30 # Ersatzdatum für 1. Mai
        - 2025-05-28 # Ersatzdatum für Auffahrt
        - 2025-12-22 # Ersatzdatum für Weihnachten


  incombustibles:
    - schedule:
        - 2025-03-13
        - 2025-06-05
        - 2025-09-11
        - 2025-12-04

  chipping_service:
    - schedule:
        - 2025-04-07
        - 2025-04-08
        - 2025-04-09
        - 2025-10-20
        - 2025-10-21
        - 2025-10-22

  special:
    - schedule:
        - 2025-01-24
        - 2025-09-12
      station: "Badi Talegg, Embrach"
    - schedule:
        - 2025-02-14
        - 2025-06-06
        - 2025-09-11
        - 2025-12-06
      station: "Einkaufszentrum Sonnenhof, Bülach"
    - schedule:
        - 2025-05-03
      station: "Werkhof, Mülistrasse 6, Lufingen"
    - schedule:
        - 2025-06-13
      station: "Werkhof, Dorfstrasse 51, Freienstein"
    - schedule:
        - 2025-12-03
      station: "Volg, Eigentalstrasse 8, Oberembrach"
    - schedule:
        - 2025-10-11
      station: "Werkhof, Tössstrasse, Rorbas"

exclude:
  # 2025
  - 2025-01-01 # Neujahr, Mittwoch
  - 2025-01-02 # Berchtoldstag, Donnerstag
  - 2025-04-18 # Karfreitag, Freitag
  - 2025-04-21 # Ostermontag, Montag
  - 2025-05-01 # 1. Mai, Donnerstag
  - 2025-05-29 # Auffahrt, Donnerstag
  - 2025-06-09 # Pfingstmontag, Montag
  - 2025-08-01 # 1. August, Freitag
  - 2025-12-25 # Weihnachten, Donnerstag
  - 2025-12-26 # Stephanstag, Freitag
