region: hombrechtikon
zip: 8634
start_date: 2025-01-01
end_date: 2026-01-03

collections:
  waste:
    - schedule:
        - weekly every Thursday
        - 2025-05-03 # Ersatzdatum für 1. Mai
        - 2025-05-31 # Ersatzdatum für Auffahrt
        - 2025-12-27 # Ersatzdatum für Weihnachten
        - 2026-01-03 # Ersatzdatum für Neujahr 2025

  bulky_goods:
    - schedule:
        - weekly every Thursday
        - 2025-05-03 # Ersatzdatum für 1. Mai
        - 2025-05-31 # Ersatzdatum für Auffahrt
        - 2025-12-27 # Ersatzdatum für Weihnachten
        - 2026-01-03 # Ersatzdatum für Neujahr 2025
  
  organic:
    - schedule:
        - every Wednesday
      exclude:
        - 2025-12-24 # keine Kartonsammlung an Heiligabend

  paper:
    - schedule:
        - 2025-03-08
        - 2025-06-21
        - 2025-11-15
  
  cardboard:
    - schedule:
        - 2025-01-13
        - 2025-03-10
        - 2025-05-19
        - 2025-07-07
        - 2025-09-08
        - 2025-11-10

  special:
    - schedule:
        - 2025-06-07
        - 2025-11-04
      station: "Sammelstelle Holflüe"

exclude:
  # 2025
  - 2025-01-01 # Neujahr, Mittwoch
  - 2025-01-02 # Berchtoldstag, Donnerstag
  - 2025-04-18 # Karfreitag, Freitag
  - 2025-04-21 # Ostermontag, Montag
  - 2025-05-01 # 1. Mai, Donnerstag
  - 2025-05-29 # Auffahrt, Donnerstag
  - 2025-06-09 # Pfingstmontag, Montag
  - 2025-08-01 # 1. August, Freitag
  - 2025-12-25 # Weihnachten, Donnerstag
  - 2025-12-26 # Stephanstag, Freitag
  - 2025-01-01 # Neujahr 2025, Donnerstag
