region: winterthur
start_date: 2025-01-01
end_date: 2025-12-31
zip: 8400

collections:
  cardboard: ~
  organic: ~
  paper: ~
  waste: ~
  metal:
    - schedule:
        - every last Wednesday in Jan, Mar, May, Jul, Sep, Nov
      description: |
        Anmeldung für die Metalltour bis spätestens 16.00 Uhr des Vortages, Tel. 052 267 68 68 oder elektronische Anmeldung.