---
waste:
  name: General waste collection
  type: waste
  description: Calendar of waste collection
  notes: Return the current calendar of the waste collection (Kehricht)
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
cardboard:
  name: Cardboard waste collection
  type: cardboard
  description: Calendar of cardboard waste collection
  notes: Return the current calendar of the cardboard waste collection (Karton)
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
organic:
  name: Organic waste collection
  type: organic
  description: Calendar of organic waste collection
  notes: Return the current calendar of the organic waste collection (Bioabfall)
  params:
  - region
  - zip
  - start
  - end
  - sort
  - offset
  - limit
  - lang
paper:
  name: Paper waste collection
  type: paper
  description: Calendar of paper waste collection
  notes: Return the current calendar of the paper waste collection (Altpapier)
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
metal:
  name: Metal waste collection
  type: metal
  description: Calendar of metal waste collection
  notes: Return the current calendar of the metal waste collection (Grobmetall)
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
special:
  name: Special waste collection
  type: special
  description: Calendar of special waste collection
  notes: Return the current calendar of the special waste collection (Sondermüll)
  params:
  - region
  - zip
  - start
  - end
  - sort
  - offset
  - limit
  - lang
textile:
  name: Textile waste collection
  type: textile
  description: Calendar of textile waste collection
  notes: Return the current calendar of the textile waste collection (Altkleider)
  params:
  - region
  - zip
  - start
  - end
  - sort
  - offset
  - limit
  - lang
cargotram:
  name: Cargotram
  type: cargotram
  description: Calendar of CargoTram
  notes: Return the current calendar of the CargoTram (Sperrmüll)
  params:
  - region
  - zip
  - station
  - start
  - end
  - sort
  - offset
  - limit
  - lang
etram:
  name: eTram
  type: etram
  description: Calendar of eTram
  notes: Return the current calendar of the eTram (electronic waste)
  params:
  - region
  - zip
  - station
  - start
  - end
  - sort
  - offset
  - limit
  - lang
chipping_service:
  name: Chipping Service
  type: chipping_service
  description: Calendar of chipping service
  notes: Return the current calendar of the chipping service
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
bulky_goods:
  name: Bulky Goods waste collection
  type: bulky_goods
  description: Calendar of bulky goods waste collection
  notes: Return the current calendar of the bulky goods waste collection (Sperrmüll)
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
incombustibles:
  name: Incombustible waste collection
  type: incombustibles
  description: Calendar of incombustible waste collection
  notes: Return the current calendar of the incombustible waste collection (Unbrennbares/Grubengut)
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
oekibus:
  name: Ökibus
  type: oekibus
  description: Calendar of Ökibus 
  notes: Return the current calendar of the Ökibus
  params:
  - region
  - zip
  - area
  - start
  - end
  - sort
  - offset
  - limit
  - lang
