plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

title: "OpenERZ Anleitung"
author:
  name: Stefan Oderbolz
  email: "odi@metaodi.ch"
description: "Hilfe zur Benutung von OpenERZ"
url: "http://metaodi.ch/openerz/"
twitter_username: "odi"
github_username:  "metaodi"
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "de"

# Build settings
markdown: kramdown
permalink: /:title/
