name: Deploy to heroku

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "openerz"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          
  update_data:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Update database
        run: ./load_data_in_database.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
