name: Deploy to heroku

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Linting
        run: npm run lint
        
      - name: Run tests
        run: npm test

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "openerz"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          
  update_data:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Validate config
        run: ./validate_config.py

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "openerz"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      
      - name: Get DATABASE_URL from heroku
        run: |
          dburl=$(heroku config:get DATABASE_URL -a openerz)
          echo "DATABASE_URL=${dburl}" >> "$GITHUB_ENV"
          
      - name: Update database
        run: ./load_data_in_database.sh
