name: Update data in database

on:
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
        
      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      
      - name: Validate config
        run: ./validate_config.py
          
      - name: Update database
        run: ./load_data_in_database.sh
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
